### ISSUE TITLE
Detect SDK 33 or higher to support Android 13 media player

### ISSUE THREAD

**Issue by Skye909** [martinmimigames/little-music-player#23]
The built in Media Player on the notification screen of Android 13 isn't activated when playing an audio file, and no notification shows either, so the audio file will play but can't be controlled.

I found Little Music Player notification doesn't show up on Android 13, possibly since it [needs to be requested](https://developer.android.com/develop/ui/views/notifications/notification-permission)?

I haven't messed with Android coding in quite a long time, but I'll see if I can fork the project and build a version of the app which checks for SDK 33 or higher and uses the Android 13 media player.

**Comment by wmartinmimi** [comment]
I see.

I'll try fixing too then.

Thanks for reporting!

**Comment by wmartinmimi** [comment]
Should be fixed in [this release](https://github.com/martinmimigames/little-music-player/releases/tag/2.8). Can you double check for me?

**Comment by wmartinmimi** [comment]
Closed it because I assumed it fixed.
Thought it might be nice to explain why I closed it.
If the issue is still here, feel free to reopen it.

**Comment by Skye909** [comment]
Hey there, 
I am sorry for the delayed response (been feeling under the weather).
I tried the new release on F-Droid and the notification does appear thanks to the new button to grant notification permission. :)
However, it still doesn't use the Android 13 media player - it's just the plain Little Music Player notification, as one would see in older Android versions too.

**Comment by wmartinmimi** [comment]
I have reopened the issue, since I haven't solved it yet. Sorry...

It seems that there is a special notification style that I didn't use. Once I learnt it, I will add it into the music player.

Thank you for telling me!

Reference for self:
Notification.MediaStyle
